CREATE DATABASE Flight_Staging;
GO

USE Flight_Staging;
GO

CREATE TABLE stg_Airlines (
    AIRLINE_CODE NVARCHAR(50), 
    AIRLINE_NAME NVARCHAR(100), 
    DOT_CODE NVARCHAR(50)
);

CREATE TABLE stg_Airports (
    AIRPORT_CODE NVARCHAR(50), 
    CITY NVARCHAR(100)
);

CREATE TABLE stg_CancelCodes (
    CANCELLATION_CODE NVARCHAR(50), 
    CANCEL_DESCRIPTION NVARCHAR(100)
);

CREATE TABLE stg_FlightStatus (
    STATUS_CODE NVARCHAR(50), 
    IS_CANCELLED INT, 
    IS_DIVERTED INT, 
    DELAY_CATEGORY NVARCHAR(50)
);

CREATE TABLE stg_FlightData (
    FL_DATE DATE, 
    FL_NUMBER NVARCHAR(50), 
    AIRLINE_CODE NVARCHAR(50), 
    ORIGIN NVARCHAR(50), 
    DEST NVARCHAR(50), 
    CANCELLATION_CODE NVARCHAR(50), 
    STATUS_CODE NVARCHAR(50), 
    DEP_DELAY INT, 
    ARR_DELAY INT, 
    DISTANCE INT
);
GO

